# Generated by Django 2.1.2 on 2018-10-14 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
